### ISSUE TITLE
[Bug] mwoffliner timer error [sf#818]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#184]
**Reported by sammyizimmy on 2015-01-20 19:51 UTC**
I am trying to dump processors.wiki.ti.com but I keep getting this timer error.
I am using node v0.10.35 and the latest mwoffliner.js.
Can you see anything obvious?

these are the option I am using
node ./mwoffliner.js --mwUrl=http://processors.wiki.ti.com --parsoidUrl=http://127.0.0.1:8000/localhost/ --mwWikiPath=/api.php --mwApiPath="/" --format=nozim --verbose

```
....
Successfuly downloaded http://processors.wiki.ti.com/skins/common/images                   /spinner.gif?2014-10-01T15:13:20Z to /home/fred/WikiDumper/mwoffliner/static/processors_en_all_2015-01/s/spinner.gif.k230s
    Trace: NODEJS FATAL EXCEPTION:TypeError: Object __X() has no method 'apply'
    at process.<anonymous> (/home/fred/WikiDumper/mwoffliner/mwoffliner.js:1441:13)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:295:26)
TypeError: Object __X() has no method 'apply'
    at listOnTimeout (timers.js:112:15)
---------------------------------------------
    at startTimer (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/browser/Window.js:23:13)
    at Window.setTimeout (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/browser/Window.js:70:48)
    at eval (eval at eval at <anonymous> (http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1:9:316))
    at http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1:9:316
    at Contextify.sandbox.run (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
    at exports.javascript (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/languages/javascript.js:5:14)
    at define.proto._eval (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:1621:47)
    at /home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:51:20
---------------------------------------------
    at ClientRequest.<anonymous> (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:129:16)
    at ClientRequest.emit (events.js:95:17)
    at parserOnIncomingClient (http.js:1693:21)
    at parserOnHeadersComplete (http.js:122:23)
    at socketOnData (http.js:1588:20)
    at onread (net.js:528:27)
/home/fred/WikiDumper/mwoffliner/mwoffliner.js:1443
    throw error;
          ^
TypeError: Object __X() has no method 'apply'
    at listOnTimeout (timers.js:112:15)
---------------------------------------------
    at startTimer (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/browser/Window.js:23:13)
    at Window.setTimeout (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/browser/Window.js:70:48)
    at eval (eval at eval at <anonymous> (http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1:9:316))
    at http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1:9:316
    at Contextify.sandbox.run (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/node_modules/contextify/lib/contextify.js:12:24)
    at exports.javascript (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/languages/javascript.js:5:14)
    at define.proto._eval (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:1621:47)
    at /home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:51:20
---------------------------------------------
    at ClientRequest.<anonymous> (/home/fred/WikiDumper/mwoffliner/node_modules/jsdom/lib/jsdom/level2/html.js:129:16)
    at ClientRequest.emit (events.js:95:17)
    at parserOnIncomingClient (http.js:1693:21)
    at parserOnHeadersComplete (http.js:122:23)
    at socketOnData (http.js:1588:20)
    at onread (net.js:528:27)
```

**Comment by rashiq** [comment]
**Commented by sammyizimmy on 2015-01-21 13:25 UTC**
Hmm. It seems to be a jsdom bug. I guess i need to try a different version...

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-01-21 13:48 UTC**
Thank you for your feedback. Unfortunately, I have no obvious answer. If the Parsoid API would be public, I would be able to test myself and probably might be able to provide a more constructive answer :)

**Comment by rashiq** [comment]
**Commented by sammyizimmy on 2015-01-21 14:57 UTC**
I "fixed" the problem. jsdom seemed to be hanging up on the http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1 java script so I added a replace function in saveJavascript to replace all references to the metrics-min.js with blank. A very ugly crutch, but it works in my case. It would be nice knowing what that actual issue is...

```
    loadUrlAsync( webUrl, function( html ) {

    html = html.replace( '<head>', '<head><base href="' + mwUrl + '" />');

+    String.prototype.replaceAll = function(str1, str2, ignore) 
+    {
+        return this.replace(new RegExp(str1.replace(/([\/\,\!\\\^\$\{\}\[\]\(\)\.\*\+\?\|\<\>\-\&])/g,"\\$&"),(ignore?"gi":"g")),(typeof(str2)=="string")?str2.replace(/\$/g,"$$$$"):str2);
+    } 
+
+    html = html.replaceAll( 'http://focus.ti.com/js/shared/metrics/metrics-min.js?version=1' , '');
```

ps: I would love to give you access to the parsiod API but I don't have the permission on this network....

**Comment by rashiq** [comment]
**Commented by sammyizimmy on 2015-01-23 15:00 UTC**
I finally got a complete dump. The latest parsoid was also needed. this ticket could probably be closed.

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-02-11 14:39 UTC**
I dont' really understand why this url makes the whole script stopping... so I feel bad without having a proper fix. Were you able in the meantime to better understand the problem?
