### ISSUE TITLE
[Bug] mwoffliner dies with "TypeError: Object #<Agent> has no method 'destroy'" [sf#897]

### ISSUE THREAD

**Issue by rashiq** [kiwix/kiwix-xulrunner#211]
**Reported by tbleher on 2015-06-30 19:43 UTC**
I just installed parsoid on my wiki (wikimedia provided Debian package (version 0.3.0) on Debian Wheezy), compiled zimwriterfs (on Ubuntu 15.04, from openzim repo, commit 440c6815d8d4e12a5f7f2ebf9c130c04e74145fd) and started mwoffliner (updated today, commit 36a056b01dc3d3b1a3d409203830d2fe9566ae73). It fails with the following output:

$ ./mwoffliner.js --mwUrl=http://spiele.j-crew.de/ --parsoidUrl=http://spiele.j-crew.de:8142/wikidb/ --adminEmail=ThomasBleher@gmx.de
Unable to download content [1] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [1] http://spiele.j-crew.de/w/skins/common/images/Checker-16x16.png?2012-03-24T06:25:00Z (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [1] http://spiele.j-crew.de/w/skins/common/images/question-small.png?2013-12-13T21:51:40Z (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [2] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [2] http://spiele.j-crew.de/w/skins/common/images/Checker-16x16.png?2012-03-24T06:25:00Z (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [2] http://spiele.j-crew.de/w/skins/common/images/question-small.png?2013-12-13T21:51:40Z (request error: Error: read ECONNRESET ).
Socket timeout
Unable to download content [3] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [4] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [5] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Absolutly unable to retrieve async. URL: Unable to download content [5] http://spiele.j-crew.de/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [1] http://spiele.j-crew.de:8142/wikidb/Polsterschlacht?oldid=12020 (statusCode=500).
TypeError: Object #<Agent> has no method 'destroy'
    at closeAgents (/home/thomas/coding/kiwix-other/mwoffliner/mwoffliner.js:540:22)
    at async.queue.path (/home/thomas/coding/kiwix-other/mwoffliner/mwoffliner.js:375:2)
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:744:13
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:46:16
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:260:32
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:37:16
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:741:17
    at /home/thomas/coding/kiwix-other/mwoffliner/mwoffliner.js:361:8
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:744:13
    at /home/thomas/coding/kiwix-other/mwoffliner/node_modules/async/lib/async.js:46:16

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-07-01 05:51 UTC**
Looks like a network/system problem or you might try with nodejs 0.12. I have started a dump and it looks (so far) good.

**Comment by rashiq** [comment]
**Updated by kelson42 on 2015-07-01 05:53 UTC**
- **labels**:  --> mwoffliner, zim
- **assigned_to**: Emmanuel Engelhart
- **Group**: v1.0 --> None

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-07-01 06:02 UTC**
I also see a few errors from Parsoid/Mediawiki:

http://spiele.j-crew.de:8142/wikidb/Diamantenfieber

Failed to parse the JSON response for Template Fetch
ParserError: Failed to parse the JSON response for Template Fetch
    at TemplateRequest.ApiRequest._handleBody (/usr/lib/parsoid/src/lib/mediawiki.ApiRequest.js:290:11)
    at TemplateRequest.ApiRequest._requestCB (/usr/lib/parsoid/src/lib/mediawiki.ApiRequest.js:249:8)
    at Request.self.callback (/usr/lib/parsoid/node_modules/request/request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/lib/parsoid/node_modules/request/request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/lib/parsoid/node_modules/request/request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:929:16
    at process._tickCallback (node.js:419:13)

I don't know if this is a problem with a server system limitation or a real error but should be investigated.

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-07-10 21:03 UTC**
Does using node v0.12 fixes the problem?

**Comment by rashiq** [comment]
**Commented by kelson42 on 2015-07-30 20:28 UTC**
Dear Thomas, I plan to close that ticket as IMO 0.12+ fixes the pb. But I would appreciate to get a confirmation from your side.
