### ISSUE TITLE
Impossible to run Kiwix custom apps with ZIM embedded (Wikimed, Wikivoyage, ...)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#266]
With the last master the custom apps do not want to start. They crash at the start and the logcat gives:

```
E/art     ( 9629): No implementation found for void org.kiwix.kiwixcustomwikimed.embedded.JNIKiwix.setDataDirectory(java.lang.String) (tried Java_org_kiwix_kiwixcustomwikimed_embedded_JNIKiwix_setDataDirectory and Java_org_kiwix_kiwixcustomwikimed_embedded_JNIKiwix_setDataDirectory__Ljava_lang_String_2)
D/AndroidRuntime( 9629): Shutting down VM
E/AndroidRuntime( 9629): FATAL EXCEPTION: main
E/AndroidRuntime( 9629): Process: org.kiwix.kiwixcustomwikimed.embedded, PID: 9629
E/AndroidRuntime( 9629): java.lang.UnsatisfiedLinkError: No implementation found for void org.kiwix.kiwixcustomwikimed.embedded.JNIKiwix.setDataDirectory(java.lang.String) (tried Java_org_kiwix_kiwixcustomwikimed_embedded_JNIKiwix_setDataDirectory and Java_org_kiwix_kiwixcustomwikimed_embedded_JNIKiwix_setDataDirectory__Ljava_lang_String_2)
E/AndroidRuntime( 9629):    at org.kiwix.kiwixcustomwikimed.embedded.JNIKiwix.setDataDirectory(Native Method)
E/AndroidRuntime( 9629):    at org.kiwix.kiwixcustomwikimed.embedded.ZimContentProvider.setIcuDataDirectory(ZimContentProvider.java:349)
E/AndroidRuntime( 9629):    at org.kiwix.kiwixcustomwikimed.embedded.ZimContentProvider.onCreate(ZimContentProvider.java:232)
E/AndroidRuntime( 9629):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
E/AndroidRuntime( 9629):    at android.content.ContentProvider.attachInfo(ContentProvider.java:1692)
E/AndroidRuntime( 9629):    at android.app.ActivityThread.installProvider(ActivityThread.java:5674)
E/AndroidRuntime( 9629):    at android.app.ActivityThread.installContentProviders(ActivityThread.java:5269)
E/AndroidRuntime( 9629):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5209)
E/AndroidRuntime( 9629):    at android.app.ActivityThread.access$1600(ActivityThread.java:181)
E/AndroidRuntime( 9629):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1535)
E/AndroidRuntime( 9629):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9629):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 9629):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime( 9629):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9629):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9629):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 9629):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
V/ApplicationPolicy( 2768): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixcustomwikimed.embedded

```

Any idea @mhutti1 @rashiq @EladKeyshawn ?

PS: We want to generate new apps currently, this would be awesom if this regression could be fixed soon!

**Comment by kelson42** [comment]
@mhutti1 Do you have a clue what has been changed here?

**Comment by mhutti1** [comment]
@kelson42 It looks like the custom apps can't find the native code. I have little understanding of the interface but can look into it when I get home tomorrow.

**Comment by kelson42** [comment]
@mhutti1 Thx, that would be awesome, I have a urgent delivery to do of the wikimed app (with everything embed)

**Comment by kelson42** [comment]
Fixed.
