### ISSUE TITLE
Impossible to run customapp with companion file

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#268]
```
D/ActivityThread( 9912): Added TimaKeyStore provider
D/kiwix   ( 9867): Kiwix Custom App starting for the first time. Check Companion ZIM.
D/kiwix   ( 9867): Looking for '/storage/emulated/0/Android/obb/org.kiwix.kiwixcustomwikimedzh/main.2.org.kiwix.kiwixcustomwikimedzh.obb' with size=146654476
D/kiwix   ( 9867): Correct file '/storage/emulated/0/Android/obb/org.kiwix.kiwixcustomwikimedzh/main.2.org.kiwix.kiwixcustomwikimedzh.obb' found.
E/art     ( 9867): No implementation found for boolean org.kiwix.kiwixcustomwikimedzh.JNIKiwix.loadZIM(java.lang.String) (tried Java_org_kiwix_kiwixcustomwikimedzh_JNIKiwix_loadZIM and Java_org_kiwix_kiwixcustomwikimedzh_JNIKiwix_loadZIM__Ljava_lang_String_2)
D/AndroidRuntime( 9867): Shutting down VM
E/AndroidRuntime( 9867): FATAL EXCEPTION: main
E/AndroidRuntime( 9867): Process: org.kiwix.kiwixcustomwikimedzh, PID: 9867
E/AndroidRuntime( 9867): java.lang.UnsatisfiedLinkError: No implementation found for boolean org.kiwix.kiwixcustomwikimedzh.JNIKiwix.loadZIM(java.lang.String) (tried Java_org_kiwix_kiwixcustomwikimedzh_JNIKiwix_loadZIM and Java_org_kiwix_kiwixcustomwikimedzh_JNIKiwix_loadZIM__Ljava_lang_String_2)
E/AndroidRuntime( 9867):    at org.kiwix.kiwixcustomwikimedzh.JNIKiwix.loadZIM(Native Method)
E/AndroidRuntime( 9867):    at org.kiwix.kiwixcustomwikimedzh.ZimContentProvider.setZimFile(ZimContentProvider.java:63)
E/AndroidRuntime( 9867):    at org.kiwix.kiwixcustomwikimedzh.KiwixMobileActivity.openZimFile(KiwixMobileActivity.java:929)
E/AndroidRuntime( 9867):    at org.kiwix.kiwixcustomwikimedzh.KiwixMobileActivity.manageExternalLaunchAndRestoringViewState(KiwixMobileActivity.java:1640)
E/AndroidRuntime( 9867):    at org.kiwix.kiwixcustomwikimedzh.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:453)
E/AndroidRuntime( 9867):    at android.app.Activity.performCreate(Activity.java:6374)
E/AndroidRuntime( 9867):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
E/AndroidRuntime( 9867):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2743)
E/AndroidRuntime( 9867):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2855)
E/AndroidRuntime( 9867):    at android.app.ActivityThread.access$900(ActivityThread.java:181)
E/AndroidRuntime( 9867):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
E/AndroidRuntime( 9867):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 9867):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 9867):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime( 9867):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9867):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 9867):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 9867):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
V/ApplicationPolicy( 2876): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixcustomwikimedzh

```

See also #266

**Comment by mhutti1** [comment]
I know that the newly compiled native code causes this error no the java and am attempting to find the commit which broke it. For now you could instead use the older already compiled native code and run gradle manually if time is important.

**Comment by kelson42** [comment]
Fixed
