### ISSUE TITLE
Crash detected by Google automated tested

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#270]
Problem : android.database.sqlite.SQLiteException: no such table: custom_from_prefs (code 1): , while compiling: SELECT \* FROM custom_from_prefs ORDER BY reply_to ASC

 FATAL EXCEPTION: Background tasks
 Process: com.google.android.gm, PID: 15302
 android.database.sqlite.SQLiteException: no such table: custom_from_prefs (code 1): , while compiling: SELECT \* FROM custom_from_prefs ORDER BY reply_to ASC
    at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
    at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:898)
    at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:509)
    at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:726)
    at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
    at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
    at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
    at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1415)
    at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:411)
    at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:305)
    at com.google.android.gm.provider.MailCore.ql(SourceFile:1188)
    at com.google.android.gm.provider.MailEngine.v(SourceFile:139)
    at com.google.android.gm.provider.bm.run(SourceFile:1327)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mhutti1** [comment]
@kelson42  No Idea whats going on here. What google automated test? com.google.android.gm is Gmail and it looks like a gmail error.

**Comment by kelson42** [comment]
it's a bug with an other app.

**Comment by BenSchZA** [comment]
I came across this crash while doing "Google" Firebase automated testing using Test Lab. It's a Firebase product that runs an app through a sequence of tests on a virtual (or sometimes hardware) device - nothing to do with your software @mhutti1.
