### ISSUE TITLE
Crashes by scrolling up/down the "local" on Android content manager

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#284]
This is almost systematic after a few time. Here is the log

```
D/ViewRootImpl( 2033): ViewPostImeInputStage ACTION_DOWN
D/InputReader( 2851): Input event: value=0
I/InputReader( 2851): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=39228121730000
I/InputDispatcher( 2851): Delivering touch to (2033): action: 0x1, toolType: 1
D/SensorService( 2851): [SO] 0.230 0.297 9.989
D/InputReader( 2851): Input event: value=1
I/InputReader( 2851): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.1639 ] when=39228743823000
D/InputReader( 2851): lastThreadEndTime = 39228122095447, currentThreadStartTime = 39228122105155
I/InputDispatcher( 2851): Delivering touch to (3090): action: 0x4, toolType: 1
I/InputDispatcher( 2851): Delivering touch to (2033): action: 0x0, toolType: 1
D/ViewRootImpl( 2033): ViewPostImeInputStage ACTION_DOWN
D/SSRM:n  ( 2851): SIOP:: AP = 330, CUR = -260
D/InputReader( 2851): Input event: value=0
I/InputReader( 2851): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=39228879668000
I/InputDispatcher( 2851): Delivering touch to (2033): action: 0x1, toolType: 1
D/AndroidRuntime( 2033): Shutting down VM
E/AndroidRuntime( 2033): FATAL EXCEPTION: main
E/AndroidRuntime( 2033): Process: org.kiwix.kiwixmobile, PID: 2033
E/AndroidRuntime( 2033): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
E/AndroidRuntime( 2033):    at org.kiwix.kiwixmobile.ZimFileSelectFragment$RescanDataAdapter.getView(ZimFileSelectFragment.java:331)
E/AndroidRuntime( 2033):    at android.widget.AbsListView.obtainView(AbsListView.java:2823)
E/AndroidRuntime( 2033):    at android.widget.ListView.makeAndAddView(ListView.java:1889)
E/AndroidRuntime( 2033):    at android.widget.ListView.fillUp(ListView.java:749)
E/AndroidRuntime( 2033):    at android.widget.ListView.fillGap(ListView.java:686)
E/AndroidRuntime( 2033):    at android.widget.AbsListView.trackMotionScroll(AbsListView.java:7037)
E/AndroidRuntime( 2033):    at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:6475)
E/AndroidRuntime( 2033):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
E/AndroidRuntime( 2033):    at android.view.Choreographer.doCallbacks(Choreographer.java:590)
E/AndroidRuntime( 2033):    at android.view.Choreographer.doFrame(Choreographer.java:559)
E/AndroidRuntime( 2033):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
E/AndroidRuntime( 2033):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 2033):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2033):    at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 2033):    at android.app.ActivityThread.main(ActivityThread.java:6117)
E/AndroidRuntime( 2033):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2033):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2033):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
E/AndroidRuntime( 2033):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
V/ApplicationPolicy( 2851): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
W/ActivityManager( 2851):   Force finishing activity org.kiwix.kiwixmobile/.ZimManageActivity
V/ApplicationPolicy( 2851): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
V/ApplicationPolicy( 2851): isApplicationStateBlocked userId 0 pkgname org.kiwix.kiwixmobile
E/android.os.Debug( 2851): ro.product_ship = true
E/android.os.Debug( 2851): ro.debug_level = 0x4f4c
W/Resources( 2851): Preloaded color resource #0x10601e6 (android:color/tw_material_blue_grey_900) that varies with configuration!!
W/Resources( 2851): Preloaded color resource #0x1060150 (android:color/tw_dialog_window_background_color_material_light) that varies with configuration!!
W/Resources( 2851): Preloaded drawable resource #0x1080a52 (android:drawable/tw_dialog_background_material) that varies with configuration!!
D/PhoneWindow( 2851): *FMB* installDecor mIsFloating : true
D/PhoneWindow( 2851): *FMB* installDecor flags : 8519682
```

**Comment by mhutti1** [comment]
Should have been fixed by 8fb768906605728a289d9f97c9705f3613c80bcb
