### ISSUE TITLE
Crash by opening the Android app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#296]
Many people - in particular with the Wikivoyage app which use the most recent code base - report crash by start with an "overlay" related error message. It's pretty unclear to me where is the problem. But I have a crash report on Google Play which maybe is related:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity}: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
    at android.app.ActivityThread.access$800(ActivityThread.java:166)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5584)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
    at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
    at java.util.ArrayList.get(ArrayList.java:308)
    at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
    at org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity.getCurrentWebView(KiwixMobileActivity.java:764)
    at org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity.loadPrefs(KiwixMobileActivity.java:1487)
    at org.kiwix.kiwixcustomwikivoyage.KiwixMobileActivity.onCreate(KiwixMobileActivity.java:456)
    at android.app.Activity.performCreate(Activity.java:5447)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
    ... 11 more
```

**Comment by mhutti1** [comment]
@kelson42 I don't think these are related at all. The overlay problem is nothing to do with our app. Its simply how android permissions work. You can't have an app like twilight on when we ask for your permission to access the SD card because it could mislead the user into granting permissions for something they don't want. It seems quite a few users don't understand this despite google telling them when they attempt to grant the permission. As for this specific crash I have pushed a potential fix.

**Comment by mhutti1** [comment]
As a side note I think the overlay problem doesn't exist in nougat as android temporarily disables overlays when requesting permissions.

**Comment by kelson42** [comment]
@mhutti1 Thank you very much. To your opion, what would be the best answer we could give to user complaining about that problem? For example, in my case, I can use both Twillight and Kiwix at the same time.

**Comment by mhutti1** [comment]
@kelson42 If a user can't disable the screen overlay temporarily to allow permission to be granted then they can manually activate it in Settings -> Apps -> Kiwix (Or custom app) -> Permissions -> Storage (This is only in marshmallow onward but this issue should only affect marshmallow users). This still requires them to disable screen overlay though so I can't see a solution if they are unable to work out the quite simple process to do this.

**Comment by mhutti1** [comment]
@kelson42 if they click the button when it pops up and then change enabled to apps with permission and then disable each app with permission to draw over screen. Then restart the Kiwix app then that should work but I think this is too complicated for users who are struggling at the moment.

**Comment by mhutti1** [comment]
As I can't reproduce this I am going to close. If it continues happening we will reopen.
