### ISSUE TITLE
Android custom app crashing by clicking on "settings"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#3]
This happens by using the git master head. Here is the tracelog:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixcustomwikivoyage/org.kiwix.kiwixcustomwikivoyage.settings.KiwixSettingsActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class org.kiwix.kiwixcustomwikivoyage.settings.SliderPreference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.access$900(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class org.kiwix.kiwixcustomwikivoyage.settings.SliderPreference
    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:443)
    at android.preference.GenericInflater.rInflate(GenericInflater.java:483)
    at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
    at android.preference.GenericInflater.inflate(GenericInflater.java:327)
    at android.preference.GenericInflater.inflate(GenericInflater.java:264)
    at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:273)
    at android.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:301)
    at org.kiwix.kiwixcustomwikivoyage.settings.KiwixSettingsActivity$PrefsFragment.onCreate(KiwixSettingsActivity.java:87)
    at android.app.Fragment.performCreate(Fragment.java:2198)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
    at android.app.BackStackRecord.run(BackStackRecord.java:793)
    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
    at android.app.FragmentController.execPendingActions(FragmentController.java:325)
    at android.app.Activity.performStart(Activity.java:6267)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    ... 9 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.kiwix.kiwixcustomwikivoyage.settings.SliderPreference" on path: DexPathList[[zip file "/data/app/org.kiwix.kiwixcustomwikivoyage-1/base.apk"],nativeLibraryDirectories=[/data/app/org.kiwix.kiwixcustomwikivoyage-1/lib/x86, /data/app/org.kiwix.kiwixcustomwikivoyage-1/base.apk!/lib/x86, /vendor/lib, /system/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
    at android.preference.GenericInflater.createItem(GenericInflater.java:376)
    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432)
    ... 24 more
    Suppressed: java.lang.ClassNotFoundException: org.kiwix.kiwixcustomwikivoyage.settings.SliderPreference
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        ... 27 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by kelson42** [comment]
Seems to be fixed.
