### ISSUE TITLE
Crash: android.view.InflateException: Binary XML file line #60: Error inflating class Button

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#302]
The Google automating testing framework reports problem (on certain devices)

```
FATAL EXCEPTION: main
 Process: org.kiwix.kiwixmobile, PID: 18020
 android.view.InflateException: Binary XML file line #60: Error inflating class Button
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
    at org.kiwix.kiwixmobile.KiwixMobileActivity$KiwixWebViewClient.onPageFinished(KiwixMobileActivity.java:1861)
    at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:456)
    at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:73)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5118)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:610)
    at dalvik.system.NativeStart.main(Native Method)
 Caused by: android.content.res.Resources$NotFoundException: File res/drawable/get_content_ripple_shape.xml from drawable resource ID #0x7f02005c
    at android.content.res.Resources.loadDrawable(Resources.java:2136)
    at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
    at android.view.View.<init>(View.java:3565)
    at android.widget.TextView.<init>(TextView.java:678)
    at android.widget.Button.<init>(Button.java:107)
    at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:62)
    at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:58)
    at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:109)
    at android.support.v7.app.AppCompatDelegateImplV7.createView(AppCompatDelegateImplV7.java:1008)
    at android.support.v7.app.AppCompatDelegateImplV7.onCreateView(AppCompatDelegateImplV7.java:1067)
    at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:684)
    ... 18 more
 Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #2: invalid drawable tag ripple
    at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
    at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
    at android.content.res.Resources.loadDrawable(Resources.java:2132)
    ... 29 more
```

**Comment by mhutti1** [comment]
@EladKeyshawn This looks to be a ripple effect crash for the welcome button.

**Comment by EladKeyshawn** [comment]
@mhutti1 oh right so we might need to target it for specific devices

**Comment by mhutti1** [comment]
@EladKeyshawn "Ripple targets minimum api 21" ours is 14. That's whats causing this issue.

**Comment by mhutti1** [comment]
@EladKeyshawn Looks like it worked but you disabled the buttons action.

**Comment by EladKeyshawn** [comment]
@mhutti1  Yeah I forgot, anyways eventually i disabled the ripple since on click itself the ripple lags 😢

**Comment by mhutti1** [comment]
@EladKeyshawn Oh well. Closing this up now.
