### ISSUE TITLE
Lots of webview warnings on last Android WikiMed app

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#334]
```
W/webview_proxy(10327): java.lang.Throwable: Warning: A WebView method was called on thread 'WebViewCoreThread'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
W/webview_proxy(10327):     at android.webkit.WebView.checkThread(WebView.java:2008)
W/webview_proxy(10327):     at android.webkit.WebView.getSettings(WebView.java:1603)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.inputStreamForAndroidResource(BrowserFrame.java:883)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.shouldInterceptRequest(BrowserFrame.java:960)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.nativeServiceFuncPtrQueue(Native Method)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:113)
W/webview_proxy(10327):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/webview_proxy(10327):     at android.os.Looper.loop(Looper.java:175)
W/webview_proxy(10327):     at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:1091)
W/webview_proxy(10327):     at java.lang.Thread.run(Thread.java:856)
D/kiwix   (10327): Retrieving: content://org.kiwix.zim.mwikimed/I/m/Gray1237.svg.png
W/webview_proxy(10327): java.lang.Throwable: Warning: A WebView method was called on thread 'WebViewCoreThread'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
W/webview_proxy(10327):     at android.webkit.WebView.checkThread(WebView.java:2008)
W/webview_proxy(10327):     at android.webkit.WebView.getSettings(WebView.java:1603)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.inputStreamForAndroidResource(BrowserFrame.java:883)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.shouldInterceptRequest(BrowserFrame.java:960)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.nativeServiceFuncPtrQueue(Native Method)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:113)
W/webview_proxy(10327):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/webview_proxy(10327):     at android.os.Looper.loop(Looper.java:175)
W/webview_proxy(10327):     at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:1091)
W/webview_proxy(10327):     at java.lang.Thread.run(Thread.java:856)
D/kiwix   (10327): Retrieving: content://org.kiwix.zim.mwikimed/I/m/Gray425.png
W/webview_proxy(10327): java.lang.Throwable: Warning: A WebView method was called on thread 'WebViewCoreThread'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
W/webview_proxy(10327):     at android.webkit.WebView.checkThread(WebView.java:2008)
W/webview_proxy(10327):     at android.webkit.WebView.getSettings(WebView.java:1603)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.inputStreamForAndroidResource(BrowserFrame.java:883)
W/webview_proxy(10327):     at android.webkit.BrowserFrame.shouldInterceptRequest(BrowserFrame.java:960)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.nativeServiceFuncPtrQueue(Native Method)
W/webview_proxy(10327):     at android.webkit.JWebCoreJavaBridge.handleMessage(JWebCoreJavaBridge.java:113)
W/webview_proxy(10327):     at android.os.Handler.dispatchMessage(Handler.java:99)
W/webview_proxy(10327):     at android.os.Looper.loop(Looper.java:175)
W/webview_proxy(10327):     at android.webkit.WebViewCore$WebCoreThread.run(WebViewCore.java:1091)
W/webview_proxy(10327):     at java.lang.Thread.run(Thread.java:856)
D/kiwix   (10327): Retrieving: content://org.kiwix.zim.mwikimed/I/s/Checker-16x16.png
D/STATUSBAR-NetworkController(  673): refreshSignalCluster: data=-1 bt=false

```

**Comment by kelson42** [comment]
@EladKeyshawn @mhutti1 Any fix in view for this warnings. I understand it's not critical, but this really makes the debugging more complicated.

**Comment by EladKeyshawn** [comment]
@kelson32 I'll try to solve this , I guess it's not only in wikimed app.

**Comment by kelson42** [comment]
@EladKeyshawn Yes, it's probably everywhere

**Comment by mhutti1** [comment]
This looks fixed to me
