### ISSUE TITLE
Kiwix for Android crash if ZIM file path contain "'"

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#37]
Example of crash log:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.kiwix.kiwixmobile/org.kiwix.kiwixmobile.SearchActivity}: android.database.sqlite.SQLiteException: near "S": syntax error (code 1): , while compiling: select \* from recentsearches where zim = '/storage/extSdCard/ab'S/APKz/Download/wikipedia_en_all_simple_2015-08.zim'
###### 

Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
    (near "S": syntax error (code 1): , while compiling: select \* from recentsearches where zim = '/storage/extSdCard/ab'S/APKz/Download/wikipedia_en_all_simple_2015-08.zim')
###### 

```
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2773)
at android.app.ActivityThread.access$900(ActivityThread.java:177)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1434)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5930)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
```

Caused by: android.database.sqlite.SQLiteException: near "S": syntax error (code 1): , while compiling: select \* from recentsearches where zim = '/storage/extSdCard/ab'S/APKz/Download/wikipedia_en_all_simple_2015-08.zim'
###### 

Error Code : 1 (SQLITE_ERROR)
Caused By : SQL(query) error or missing database.
    (near "S": syntax error (code 1): , while compiling: select \* from recentsearches where zim = '/storage/extSdCard/ab'S/APKz/Download/wikipedia_en_all_simple_2015-08.zim')
###### 

```
at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1093)
at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:670)
at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1393)
at org.kiwix.kiwixmobile.utils.DatabaseHelper.getRecentSearches(DatabaseHelper.java:82)
at org.kiwix.kiwixmobile.SearchActivity.onCreate(SearchActivity.java:47)
at android.app.Activity.performCreate(Activity.java:6178)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
... 10 more
```

The solution: values given to sqlite should be SQL escaped or use any other SQL solution to avoid this kind of problem with special characters.

**Comment by EladKeyshawn** [comment]
@kelson42 Interesting, i made a function to escape the SQL but used it just for the recent searches. I'll take a look into this and try to apply the function to the ZIM file.

**Comment by kelson42** [comment]
@EladKeyshawn Great, if you can just call that function everytime needed in the app, that would be helpful to fix that bug IMO.

**Comment by kelson42** [comment]
Seems to work well with my tests. Thx!

**Comment by kelson42** [comment]
I reopen the problem because I have remarked that the search history is always empty in the case the ZIM filename has a quote. But it works if the filename does not have a quote in the filename. IMO the SQL escaping should also be to the bookmark related SQL requests.

**Comment by EladKeyshawn** [comment]
Hey @kelson42 can you give more specific details of how to reproduce the problem?

**Comment by kelson42** [comment]
This fixes the problem. Thx @EladKeyshawn
