### ISSUE TITLE
Pretty much crashes with Android 4.1 (on Google Play)

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#439]
```
java.lang.ClassCastException: org.kiwix.kiwixmobile.ZimFileSelectFragment$RescanDataAdapter cannot be cast to android.widget.HeaderViewListAdapter
	at android.widget.ListView.removeFooterView(ListView.java:393)
	at org.kiwix.kiwixmobile.ZimFileSelectFragment$1$2.run(ZimFileSelectFragment.java:241)
	at android.os.Handler.handleCallback(Handler.java:615)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4921)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
	at dalvik.system.NativeStart.main(Native Method)
```

Can be tested with
* Galaxy Note (GT-N7000) 1
* Galaxy Note 10.1 (p4noterf)

**Comment by kelson42** [comment]
@EladKeyshawn Thank you for your fix. I do not have a reprocase for this... so I cross the fingers :)
