### ISSUE TITLE
Android crash with master head

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#448]
I have achieved to get an app systematically crashing by click on "get content'

```
01-29 11:10:39.284  2812  3461 D MotionRecognitionService:  ssp status : false
01-29 11:10:39.319 14073 14073 W ResourceType: Failure getting entry for 0x01080a98 (t=7 e=2712) (error -75)
01-29 11:10:39.319 14073 14073 W ResourceType: Failure getting entry for 0x01080a98 (t=7 e=2712) (error -75)
01-29 11:10:39.319 14073 14073 D AbsListView: Get MotionRecognitionManager
01-29 11:10:39.329 14073 14073 D AndroidRuntime: Shutting down VM
01-29 11:10:39.334 14073 14073 E AndroidRuntime: FATAL EXCEPTION: main
01-29 11:10:39.334 14073 14073 E AndroidRuntime: Process: org.kiwix.kiwixmobile, PID: 14073
01-29 11:10:39.334 14073 14073 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.Filter org.kiwix.kiwixmobile.library.LibraryAdapter.getFilter()' on a null object reference
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at org.kiwix.kiwixmobile.LibraryFragment.downloadFile(LibraryFragment.java:295)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at org.kiwix.kiwixmobile.LibraryFragment.onCreateView(LibraryFragment.java:132)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.Fragment.performCreateView(Fragment.java:2281)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:984)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1164)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.BackStackRecord.run(BackStackRecord.java:793)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1557)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:568)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.v13.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:149)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:671)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1319)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:736)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6333)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3140)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.View.measure(View.java:20236)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2704)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1656)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1948)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1544)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7602)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:622)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7331)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
01-29 11:10:39.334 14073 14073 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
01-29 11:10:39.334  2812  3474 W ActivityManager:   Force finishing activity org.kiwix.kiwixmobile/.ZimManageActivity
01-29 11:10:39.334  2812  3474 D InputDispatcher: Focused application set to: xxxx
01-29 11:10:39.339  2812  3474 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
01-29 11:10:39.339  2812  3474 W ActivityManager:   Force finishing activity org.kiwix.kiwixmobile/.KiwixMobileActivity
01-29 11:10:39.344  2812  3474 D InputDispatcher: Focused application set to: xxxx
01-29 11:10:39.344  2812  3474 D FocusedStackFrame: Set to : 0
01-29 11:10:39.349 14073 14233 D android-storage-devices: Unable to create marker file, duplicates may be listed
01-29 11:10:39.364  2812 14236 E android.os.Debug: ro.product_ship = true
01-29 11:10:39.364  2812 14236 E android.os.Debug: ro.debug_level = 0x4f4c
01-29 11:10:39.364  2812 14236 E android.os.Debug: sys.mobilecare.preload = false
01-29 11:10:39.364  2812  2885 W Resources: Preloaded color resource #0x1060158 (android:color/tw_dialog_window_background_color_material_light) that varies with configuration!!
01-29 11:10:39.364  2812  2885 W Resources: Preloaded drawable resource #0x1080a04 (android:drawable/tw_dialog_background_material) that varies with configuration!!
01-29 11:10:39.364  2812  2885 W Resources: Preloaded color resource #0x10601df (android:color/hint_foreground_material_light) that varies with configuration!!
01-29 11:10:39.364  2812  2885 W Resources: Preloaded color resource #0x10601a2 (android:color/link_text_device_default_light) that varies with configuration!!
01-29 11:10:39.364  2812  2885 W Resources: Preloaded color resource #0x10601df (android:color/hint_foreground_material_light) that varies with configuration!!
01-29 11:10:39.364  2812  2885 W Resources: Preloaded color resource #0x10601a2 (android:color/link_text_device_default_light) that varies with configuration!!

```

**Comment by EladKeyshawn** [comment]
@kelson42 I tried now and it doesn't seem to crash. Do you have more specific repro steps?

**Comment by mhutti1** [comment]
@kelson42 Should be fixed now.

**Comment by kelson42** [comment]
@mhutti1 @EladKeyshawn I have uninstall the app, so I can not retest it. But thx @mhutti1
