### ISSUE TITLE
Problem to uploat APK with upload-apk.py

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#453]
After #451 has been fixed, I face now a new problem by uploading the files to Google Play. I hardly believe this is related, but this seems to definitely be a regression;

```
$ ./upload-apk.py custom/phet/info.json 
INFO:__main__:Uploading org.kiwix.kiwixcustomphet APK to play_store:alpha
INFO:__main__:Starting Google Play Store using alpha
Traceback (most recent call last):
  File "./upload-apk.py", line 241, in <module>
    main(jspath, *args)
  File "./upload-apk.py", line 231, in main
    STORES.get(store)(jsdata, channel=channel)
  File "./upload-apk.py", line 161, in upload_to_play_store
    copy_to(jsdata['zim_file'], comp_file)
  File "./upload-apk.py", line 102, in copy_to
    shutil.copy(src, dst)
  File "/usr/lib/python3.5/shutil.py", line 235, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.5/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'content.zim'

```

**Comment by mhutti1** [comment]
The issue is that the script is not configured for remote/relative file paths.

**Comment by kelson42** [comment]
@mhutti1 The problem appeared by trying to upload a new beta of the PhEts app based on http://download.kiwix.org/zim/phet/phet_mul_2017-02.zim
