### ISSUE TITLE
  java.lang.NullPointerException in org.kiwix.kiwixmobile.ZimContentProvider.getName

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-xulrunner#467]
Can that be that the app dies if no name in ZIM metadata?
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.kiwix.kiwixmobile.ZimContentProvider.getName(ZimContentProvider.java:180)
	at org.kiwix.kiwixmobile.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1420)
	at org.kiwix.kiwixmobile.KiwixMobileActivity.onPrepareOptionsMenu(KiwixMobileActivity.java:1405)
	at android.app.Activity.onPreparePanel(Activity.java:2970)
	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:547)
	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:536)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
	at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5940)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
	at org.kiwix.kiwixmobile.ZimContentProvider.getName(ZimContentProvider.java:180)
	at org.kiwix.kiwixmobile.KiwixMobileActivity.refreshBookmarkSymbol(KiwixMobileActivity.java:1420)
	at org.kiwix.kiwixmobile.KiwixMobileActivity.onPrepareOptionsMenu(KiwixMobileActivity.java:1405)
	at android.app.Activity.onPreparePanel(Activity.java:2970)
	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:547)
	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:536)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:297)
	at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:93)
	at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:567)
	at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
	at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
	at android.view.Choreographer.doFrame(Choreographer.java:559)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5940)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
```

**Comment by EladKeyshawn** [comment]
@kelson42 Did that solve this?

**Comment by kelson42** [comment]
@EladKeyshawn Thx you. I do not have a reprocase. This trace comes from Play store admin. I suspect a deal with an "old" zim file (without this name metatag).

@mhutti1 Have you had a look to the other ones?

**Comment by mhutti1** [comment]
I think we have got most if not all of them.
